### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by disdaining** [kratzert/finetune_alexnet_with_tensorflow#4] opened 2017-05-19 11:37 UTC
Hi,
I tried reproducing the example keeping it as simple as possible. I have **train.txt** as:
images/cat1.png 0
images/cat2.png 0
images/cat3.png 0
images/dog1.png 1
images/dog2.png 1
images/dog3.png 1
And **test.txt** as:
images/cat4.png 0
images/dog4.png 1
when i run the finetune.py i get this error:
Traceback (most recent call last):
  File "finetune.py", line 163, in <module>
    test_acc /= test_count
ZeroDivisionError: float division by zero
Tried debugging the error and found that **val_batches_per_epoch** is 0 and the inner body isn't executing.

**Comment by kratzert** [comment] 2017-05-19 11:44
you mean literally only 2 images in the test set and 6 in the train set for this example? What is the batch_size you chose? if you look at the line, how the val_batches_per_epoch is calculated

`val_batches_per_epoch = np.floor(val_generator.data_size / batch_size).astype(np.int16)`

you can see, that I used np.floor for the cases, where the total data size is not a multiple of your batch_size. So if your batch_size is any bigger that 2 for this particular case, you will get a val_batches_per_epoch of 0.

**Comment by disdaining** [comment] 2017-05-19 11:47
This is just for illustration purpose, i have another problem which has thousands of images. I selected batch_size as 8 based on total number of images. Sorry am a newbie and trying to make it run on a basic example.

**Comment by kratzert** [comment] 2017-05-19 11:59
Strange. Did you make any changes to the code? Please copy the entire settings part here (upper part of the finetune.py till display_step) and the output of val_generator.data_size. You could just run the code until the beginning of the session and extract the val_generator.data_size value and post everything here. This shouldn't happen and does not for me, so there must be anything wrong with the settings or the data reading.

**Comment by disdaining** [comment] 2017-05-19 12:13
yes, its working now. 

I have separately printed testing accuracy as:
`        test_acc /= test_count
        print("Validation Accuracy = {:.4f}".format(datetime.now(), test_acc))
        print("Testing Accuracy = ", test_acc)
        print("\n")`

In the final epoch of results, i got testing accuracy as 1.0 

How can i interpret outputs of /tmp/finetune_alexnet/ and dogs_vs_cats folder?
Thank you

**Comment by kratzert** [comment] 2017-05-19 12:19
So everything works, also for your own data?

There were some missing brackets in the print statement of the validation accuracy. I did a fix right now, so download the latest commit.

The outputs in the /tmp/finetune_alexnet folder are 
- TensorBoard log files, so you can observe the training process in TensorBoard
- Model Checkpoints used for restoring a trained network state

**Comment by disdaining** [comment] 2017-05-19 13:36
Yes, that was missing. I was wondering why there is no value for Accuracy.
Not for my data. I haven't tried my data yet because the nature of my data is a bit different. In my data, i have images as input and some floating point numbers as output. For instance, take an image of a car and mileage per gallon along with other floating point numbers as features, to classify good and bad cars.
Apart from the tensorboard log files, how can i output testing accuracy for a specific test image along with the predicted label?  Like:
Image = Cat04.png
Testing Accuracy = 1.0
Label(s) = cat
And for better interpretation can be used in a graph.

**Comment by kratzert** [comment] 2017-05-20 15:01
Okay, I'll close this here, since this is not an issue anymore with finetuning AlexNet and this repository.

As for your problem: floating point as input or output? If as output you must change the last layer (the softmax) and think of another output layer (e.g. linear). If you have additional floating point numbers as input you have to change the networks architecture even more, because you have to think of how to fuse additional inputs into the network since AlexNet was designed for one image only. And how to classify one image, well just have a look how it's done in the code to calculate the validation accuracy.

**Closed as completed by kratzert** 2017-05-20 15:01 UTC

**Comment by micklexqg** [comment] 2017-08-20 03:28
So, how to solve the problem if  val_batches_per_epoch is 0 (batch_size is 128, val_generator.data_size is 100)?
always the error,
 ZeroDivisionError: float division by zero...
